<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }} Export</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .filters {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f5f5f5;
            border-radius: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #4a5568;
            color: white;
            padding: 10px;
            text-align: left;
            font-size: 12px;
        }
        td {
            padding: 8px;
            border: 1px solid #ddd;
            font-size: 11px;
        }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .status-active { color: green; font-weight: bold; }
        .status-inactive { color: red; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }} Report</h1>
        <p>Generated on: {{ now()->format('F j, Y H:i:s') }}</p>
        <p>Total Records: {{ $data->count() }}</p>
    </div>

    @if(!empty($filters))
    <div class="filters">
        <h4>Applied Filters:</h4>
        <ul>
            @foreach($filters as $key => $value)
                @if($value)
                    <li><strong>{{ ucfirst($key) }}:</strong> {{ is_array($value) ? implode(', ', $value) : $value }}</li>
                @endif
            @endforeach
        </ul>
    </div>
    @endif

    <table>
        <thead>
            <tr>
                @foreach($headings as $heading)
                    <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($data as $row)
                <tr>
                    @foreach($row as $value)
                        <td>{{ is_array($value) ? implode(', ', $value) : $value }}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by {{ auth()->user()->name }} | {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
